# Generated by Django 4.2.13 on 2024-05-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinutasCasei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulominuta', models.CharField(max_length=200, verbose_name='Titulo de la Minuta')),
                ('fechaminuta', models.DateField(verbose_name='Fecha de la Minuta')),
                ('minuta', models.TextField(verbose_name='Minuta')),
                ('acuerdos', models.TextField(verbose_name='Acuerdos')),
            ],
        ),
    ]
