# Generated by Django 4.2.13 on 2024-05-13 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_documento'),
        ('minuta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMinuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseiuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.caseiuser', verbose_name='UsuarioCasei')),
                ('minuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minuta.minutascasei', verbose_name='MinutaCasei')),
            ],
        ),
    ]
